### ISSUE TITLE
the error variance used in divand

### ISSUE THREAD

**Issue by JianghuiDu** [gher-ulg/DIVAnd.jl#18]
The documentation states that 
```
epsilon2: error variance of the observations (normalized by the error variance of the background field). 
epsilon2 can be a scalar (all observations have the same error variance and their errors are decorrelated),
 a vector (all observations can have a different error variance and their errors are decorrelated) or a matrix 
(all observations can have a different error variance and their errors can be correlated). If epsilon2 is a 
scalar, it is thus the inverse of the signal-to-noise ratio.
```
So what is a reasonable number? And what is the variance of the background field if the background is simply taken as the mean of the observations?
Suppose I have `N` observations `[x1,x2,...,xN]` each has an measurement uncertainty (variance) of `[e1^2, e2^2,...,eN^2]`. The variance of the mean of the observations is `s^2 = var([x1,x2,...,xN])`, is it reasonable to let `epsilon2 = [e1^2, e2^2,...,eN^2]/s^2`. I understand the `epsilon2` can be optimized but I'd like to know what best a priori setting  should be. Thanks!

**Comment by Alexander-Barth** [comment]
If you are familiar with the Data Assimilation notation (http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.361.9263&rep=rep1&type=pdf) , this parameter is essential `diag(R) ./ diag(P)` where `R` is the error covariance of the observation (assumed to be diagonally if `espilon2` is a scalar or vector) and `P` is the error covariance of the background estimate.

Your interpretation is indeed correct. In practise one does often not have directly the matrix R (or your e1, e2, ...). So instead of trying to estimate e1^2,... and s^2 , we are trying to estimate directly their ratio, because only their ratio affect the end-result.

The value of this parameter depends on your case, but when deriving ocean climatologies for physical variables values of 1 or 0.1 are quite typical.
