### ISSUE TITLE
optimize correlation length scale for horizontal dimensions

### ISSUE THREAD

**Issue by JianghuiDu** [gher-ulg/DIVAnd.jl#48]
Regarding 2D lat-lon analysis. Two questions:

1. Is it possible to optimize the correlation length scales for both latitude and longitude? I know how to optimize `len = (len_lat,len_lon)*scale` using `bestfactorl` given by`DIVAnd_cv`. But I'd like to have `len = (len_lat*scale_lat, len_lon*scale_lon)` and optimize both `scale_lat` and `scale_lon`. 

2. It appears when using `DIVAnd_cv` the ranges explored are always between `10^-1.5` and `10^1.5` for `epsilon2` and `10^-1` and `10^1` for `len` regardless of `nl` and `ne`. So is it possible to expand the search area and what exactly do those two numbers control?

**Comment by jmbeckers** [comment]
1. We did not implement an independant optimization of Lx and Ly assuming that if you know there is an anisotripy, you should be able to specify it to some extend. Otherwise you are adding one more free parameter to calibrate. If you really want to implement it you would need to adapt DIVAnd_cv (but again with all the limitations inherent to the method)

2. Those numbers just controlling the width in L and epsilon space over which you search an optimum. If you want a larger domain you can either manually increase the values in DIVAnd_cv OR move the search window by hand (providing different input values for the central values of L and epsilon)

**Comment by jmbeckers** [comment]
For the moment, if you really would like to explore the possibility to calibrate both Lx and Ly is to let DIVAnd_cv optimize around that value and then only change by hand the value of Lx for example increase and redo. If you find a better optimum, you are going into the right anistropy direction. If it worsens, change the value of Lx into a lower value than the original one and retry.
